plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.38,8)'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

group = project.group
description = project.displayname
version = project.version

base {
    archivesName = project.name + 'Forge'
}

minecraft {
    accessTransformer = true
    facade = files('src/main/resources/presencefootsteps.facade.cfg')

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'

            args '--mixin.config=presencefootsteps.mixin.json'
        }

        register('client')
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
//    maven {
//        name = 'Fabric'
//        url = 'https://maven.fabricmc.net/'
//    }
//    maven { name 'minelp'; url 'https://repo.minelittlepony-mod.com/maven/snapshot' }
//    maven { name 'minelp-release'; url 'https://repo.minelittlepony-mod.com/maven/release' }
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:26.2-65.1.3')
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.6'

//    implementation("com.minelittlepony:kirin:1.22.0+26.2") {
//        exclude group: "net.fabricmc.fabric-api"
//    }
}

tasks.named('jar', Jar) {
    manifest {
        attributes(['MixinConfigs': 'presencefootsteps.mixin.json'])
    }
}
