org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

org.gradle.isolated-projects=true

net.minecraftforge.gradle.merge-source-sets=true

# Mod Properties
  group=com.presencefootsteps
  displayname=Presence Footsteps
  authors=Hurricaaane (Ha3), Sollace, Paint_Ninja
  description=An overly complicated sound mod
  url=http://presencefootsteps.ha3.eu
  version=26.2-1.13.3
